<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">dateDiff</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQoNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOw0KCURhdGUJYmVmb3JlRGF0ZSA9IChEYXRlKUlEYXRhVXRpbC5nZXQoIHBpcGVs
aW5lQ3Vyc29yLCAiYmVmb3JlRGF0ZSIgKTsNCglEYXRlCWFmdGVyRGF0ZSA9IChEYXRlKUlEYXRh
VXRpbC5nZXQoIHBpcGVsaW5lQ3Vyc29yLCAiYWZ0ZXJEYXRlIiApOw0KcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw0KDQpsb25nIGRpZmYgPSBhZnRlckRhdGUuZ2V0VGltZSgpIC0gYmVmb3JlRGF0
ZS5nZXRUaW1lKCk7DQpTdHJpbmcgZWxhcHNlZE1pbGxpU2VjID0gTG9uZy50b1N0cmluZyhkaWZm
KTsNCgkJDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImVsYXBz
ZWRNaWxsaVNlYyIsIGVsYXBzZWRNaWxsaVNlYyApOw0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95
KCk7DQoNCgk=</value>
</Values>
