<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">multiConcat</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCglTdHJpbmdbXQlpbnB1dExpc3QgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nQXJyYXko
IHBpcGVsaW5lQ3Vyc29yLCAiaW5wdXRMaXN0IiApOw0KCVN0cmluZwlzZXBhcmF0b3IgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInNlcGFyYXRvciIgKTsNCnBpcGVsaW5l
Q3Vyc29yLmRlc3Ryb3koKTsNCg0KU3RyaW5nQnVmZmVyIHNiID0gbmV3IFN0cmluZ0J1ZmZlcigp
Ow0KZm9yIChpbnQgaSA9IDA7IGkgPCBpbnB1dExpc3QubGVuZ3RoOyBpKyspIHsNCglzYi5hcHBl
bmQoaW5wdXRMaXN0W2ldKTsNCglpZigoaSsxKSA8IGlucHV0TGlzdC5sZW5ndGgpDQoJCXNiLmFw
cGVuZChzZXBhcmF0b3IpOw0KDQp9DQoJDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxp
bmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3JfMSwgImNvbmNhdFN0cmluZyIsIHNiLnRvU3RyaW5nKCkgKTsNCnBpcGVsaW5lQ3Vy
c29yXzEuZGVzdHJveSgpOw0KDQoJ</value>
</Values>
