<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToBigDecimal</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0
cmluZwlpblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5T
dHJpbmciICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCnRyeSB7DQoJDQoJaW5TdHJp
bmcgPSBpblN0cmluZy50cmltKCk7DQoJZmluYWwgRGVjaW1hbEZvcm1hdCBmb3JtYXQgPSBuZXcg
RGVjaW1hbEZvcm1hdCgpOw0KCWZvcm1hdC5zZXRQYXJzZUJpZ0RlY2ltYWwodHJ1ZSk7DQoJDQog
ICAgZmluYWwgTnVtYmVyIG51bWJlciA9IGZvcm1hdC5wYXJzZShpblN0cmluZyk7DQogICAgQmln
RGVjaW1hbCBvdXRCaWdEZWNpbWFsID0gbmV3IEJpZ0RlY2ltYWwobnVtYmVyLnRvU3RyaW5nKCkp
Ow0KICAgIA0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAib3V0QmlnRGVjaW1hbCIs
IG91dEJpZ0RlY2ltYWwgKTsNCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsJDQogIA0KfSBj
YXRjaCAoUGFyc2VFeGNlcHRpb24gaWdub3JlKSB7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oInVuYWJsZSB0byBjb252ZXJ0IHZhbHVlIDogIiArIGluU3RyaW5nKTsNCn0NCgk=</value>
</Values>
